module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "city1_blue.png",
				spriteColorRect = { x = 13, y = 16, width = 40, height = 48 }, 
				textureRect = { x = 0, y = 64, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city1_grey.png",
				spriteColorRect = { x = 13, y = 16, width = 40, height = 48 }, 
				textureRect = { x = 64, y = 64, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city1_red.png",
				spriteColorRect = { x = 13, y = 16, width = 40, height = 48 }, 
				textureRect = { x = 128, y = 0, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city2_blue.png",
				spriteColorRect = { x = 3, y = 1, width = 60, height = 62 }, 
				textureRect = { x = 0, y = 0, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city2_grey.png",
				spriteColorRect = { x = 3, y = 1, width = 60, height = 62 }, 
				textureRect = { x = 0, y = 128, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city2_red.png",
				spriteColorRect = { x = 3, y = 1, width = 60, height = 62 }, 
				textureRect = { x = 128, y = 128, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city3_blue.png",
				spriteColorRect = { x = 6, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 64, y = 128, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city3_grey.png",
				spriteColorRect = { x = 6, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 128, y = 64, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
			{
				name = "city3_red.png",
				spriteColorRect = { x = 6, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 64, y = 0, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = false,
				textureRotated = false
			},
		
		}
	}

	return sheet
end