module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "arrow_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 0, y = 0, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "arrow_crossed_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 0, y = 66, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "arrow_crossed_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 66, y = 0, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "arrow_disabled_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 60, y = 132, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "arrow_disabled_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 60, y = 132, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "arrow_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 132, y = 0, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "arrow_selected_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 198, y = 0, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "arrow_selected_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 }, 
				textureRect = { x = 126, y = 118, width = 64, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "cemetery_blue.png",
				spriteColorRect = { x = 17, y = 3, width = 32, height = 58 }, 
				textureRect = { x = 40, y = 394, width = 32, height = 58 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "cemetery_red.png",
				spriteColorRect = { x = 17, y = 3, width = 32, height = 58 }, 
				textureRect = { x = 242, y = 300, width = 32, height = 58 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city1_blue.png",
				spriteColorRect = { x = 7, y = 16, width = 38, height = 48 }, 
				textureRect = { x = 168, y = 300, width = 38, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city1_grey.png",
				spriteColorRect = { x = 7, y = 16, width = 38, height = 48 }, 
				textureRect = { x = 0, y = 392, width = 38, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city1_red.png",
				spriteColorRect = { x = 7, y = 16, width = 38, height = 48 }, 
				textureRect = { x = 48, y = 344, width = 38, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city2_blue.png",
				spriteColorRect = { x = 1, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 184, y = 184, width = 56, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city2_grey.png",
				spriteColorRect = { x = 1, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 126, y = 184, width = 56, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city2_red.png",
				spriteColorRect = { x = 1, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 0, y = 278, width = 56, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city3_blue_01.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 }, 
				textureRect = { x = 314, y = 0, width = 48, height = 62 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city3_blue_02.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 }, 
				textureRect = { x = 264, y = 64, width = 48, height = 62 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city3_grey.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 }, 
				textureRect = { x = 314, y = 64, width = 48, height = 62 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city3_red_01.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 }, 
				textureRect = { x = 212, y = 66, width = 48, height = 62 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "city3_red_02.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 }, 
				textureRect = { x = 264, y = 0, width = 48, height = 62 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "fortress_wall_blue.png",
				spriteColorRect = { x = 4, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 62, y = 244, width = 56, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "fortress_wall_red.png",
				spriteColorRect = { x = 4, y = 0, width = 56, height = 64 }, 
				textureRect = { x = 62, y = 244, width = 56, height = 64 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "item.png",
				spriteColorRect = { x = 13, y = 13, width = 38, height = 38 }, 
				textureRect = { x = 120, y = 350, width = 38, height = 38 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "item_giant.png",
				spriteColorRect = { x = 8, y = 8, width = 48, height = 48 }, 
				textureRect = { x = 170, y = 250, width = 48, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "item_mine.png",
				spriteColorRect = { x = 8, y = 8, width = 48, height = 48 }, 
				textureRect = { x = 120, y = 250, width = 48, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "item_skeleton.png",
				spriteColorRect = { x = 8, y = 8, width = 48, height = 48 }, 
				textureRect = { x = 288, y = 128, width = 48, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "item_tornado.png",
				spriteColorRect = { x = 8, y = 8, width = 48, height = 48 }, 
				textureRect = { x = 238, y = 130, width = 48, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_01.png",
				spriteColorRect = { x = 19, y = 1, width = 26, height = 42 }, 
				textureRect = { x = 88, y = 198, width = 26, height = 42 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_02.png",
				spriteColorRect = { x = 19, y = 5, width = 26, height = 42 }, 
				textureRect = { x = 192, y = 350, width = 26, height = 42 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_03.png",
				spriteColorRect = { x = 19, y = 9, width = 26, height = 44 }, 
				textureRect = { x = 60, y = 198, width = 26, height = 44 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_04.png",
				spriteColorRect = { x = 19, y = 13, width = 26, height = 40 }, 
				textureRect = { x = 208, y = 308, width = 26, height = 40 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_05.png",
				spriteColorRect = { x = 19, y = 17, width = 26, height = 36 }, 
				textureRect = { x = 192, y = 394, width = 26, height = 36 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_06.png",
				spriteColorRect = { x = 18, y = 21, width = 28, height = 32 }, 
				textureRect = { x = 58, y = 310, width = 28, height = 32 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_07.png",
				spriteColorRect = { x = 20, y = 25, width = 24, height = 28 }, 
				textureRect = { x = 302, y = 352, width = 24, height = 28 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_08.png",
				spriteColorRect = { x = 22, y = 29, width = 20, height = 24 }, 
				textureRect = { x = 146, y = 466, width = 20, height = 24 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_09.png",
				spriteColorRect = { x = 22, y = 29, width = 20, height = 24 }, 
				textureRect = { x = 146, y = 466, width = 20, height = 24 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_10.png",
				spriteColorRect = { x = 23, y = 33, width = 18, height = 20 }, 
				textureRect = { x = 192, y = 118, width = 18, height = 20 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_11.png",
				spriteColorRect = { x = 27, y = 35, width = 10, height = 18 }, 
				textureRect = { x = 192, y = 162, width = 10, height = 18 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_12.png",
				spriteColorRect = { x = 29, y = 37, width = 6, height = 16 }, 
				textureRect = { x = 116, y = 198, width = 6, height = 16 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_13.png",
				spriteColorRect = { x = 29, y = 41, width = 8, height = 12 }, 
				textureRect = { x = 66, y = 118, width = 8, height = 12 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_14.png",
				spriteColorRect = { x = 30, y = 45, width = 6, height = 6 }, 
				textureRect = { x = 76, y = 118, width = 6, height = 6 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_create_15.png",
				spriteColorRect = { x = 29, y = 49, width = 6, height = 2 }, 
				textureRect = { x = 84, y = 118, width = 6, height = 2 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_explode_01.png",
				spriteColorRect = { x = 19, y = 26, width = 28, height = 28 }, 
				textureRect = { x = 120, y = 390, width = 28, height = 28 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_explode_02.png",
				spriteColorRect = { x = 10, y = 5, width = 46, height = 48 }, 
				textureRect = { x = 120, y = 300, width = 46, height = 48 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_explode_03.png",
				spriteColorRect = { x = 6, y = 0, width = 56, height = 50 }, 
				textureRect = { x = 128, y = 66, width = 56, height = 50 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_explode_04.png",
				spriteColorRect = { x = 2, y = 0, width = 60, height = 50 }, 
				textureRect = { x = 66, y = 66, width = 60, height = 50 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_explode_05.png",
				spriteColorRect = { x = 2, y = 16, width = 60, height = 32 }, 
				textureRect = { x = 0, y = 244, width = 60, height = 32 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_triggered_01.png",
				spriteColorRect = { x = 29, y = 49, width = 6, height = 2 }, 
				textureRect = { x = 84, y = 118, width = 6, height = 2 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_triggered_02.png",
				spriteColorRect = { x = 30, y = 45, width = 6, height = 6 }, 
				textureRect = { x = 76, y = 118, width = 6, height = 6 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_triggered_03.png",
				spriteColorRect = { x = 29, y = 41, width = 8, height = 12 }, 
				textureRect = { x = 66, y = 118, width = 8, height = 12 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_triggered_04.png",
				spriteColorRect = { x = 29, y = 37, width = 6, height = 16 }, 
				textureRect = { x = 116, y = 198, width = 6, height = 16 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_triggered_05.png",
				spriteColorRect = { x = 27, y = 35, width = 10, height = 18 }, 
				textureRect = { x = 192, y = 162, width = 10, height = 18 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "mine_triggered_06.png",
				spriteColorRect = { x = 23, y = 33, width = 18, height = 20 }, 
				textureRect = { x = 192, y = 118, width = 18, height = 20 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "pause.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 46 }, 
				textureRect = { x = 0, y = 344, width = 46, height = 46 }, 
				spriteSourceSize = { width = 46, height = 46 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "tornado_01.png",
				spriteColorRect = { x = 4, y = 4, width = 58, height = 54 }, 
				textureRect = { x = 0, y = 132, width = 58, height = 54 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "tornado_02.png",
				spriteColorRect = { x = 6, y = 3, width = 54, height = 58 }, 
				textureRect = { x = 242, y = 180, width = 54, height = 58 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "tornado_03.png",
				spriteColorRect = { x = 4, y = 5, width = 58, height = 54 }, 
				textureRect = { x = 0, y = 188, width = 58, height = 54 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "tornado_04.png",
				spriteColorRect = { x = 6, y = 3, width = 54, height = 58 }, 
				textureRect = { x = 242, y = 240, width = 54, height = 58 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_down_blue_01.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 172, y = 432, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_down_blue_02.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 298, y = 178, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_down_red_01.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 220, y = 408, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_down_red_02.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 220, y = 350, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_left_blue_01.png",
				spriteColorRect = { x = 12, y = 7, width = 30, height = 56 }, 
				textureRect = { x = 88, y = 368, width = 30, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_left_blue_02.png",
				spriteColorRect = { x = 18, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 120, y = 420, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_left_red_01.png",
				spriteColorRect = { x = 12, y = 7, width = 30, height = 56 }, 
				textureRect = { x = 88, y = 310, width = 30, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_left_red_02.png",
				spriteColorRect = { x = 18, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 32, y = 454, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_right_blue_01.png",
				spriteColorRect = { x = 23, y = 7, width = 30, height = 56 }, 
				textureRect = { x = 160, y = 350, width = 30, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_right_blue_02.png",
				spriteColorRect = { x = 23, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 276, y = 300, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_right_red_01.png",
				spriteColorRect = { x = 23, y = 7, width = 30, height = 56 }, 
				textureRect = { x = 0, y = 442, width = 30, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_right_red_02.png",
				spriteColorRect = { x = 23, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 74, y = 426, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_up_blue_01.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 268, y = 360, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_up_blue_02.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 220, y = 250, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_up_red_01.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 298, y = 236, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_attack_up_red_02.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 194, y = 432, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_carry_blue.png",
				spriteColorRect = { x = 18, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 120, y = 420, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_carry_red.png",
				spriteColorRect = { x = 23, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 74, y = 426, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_down_blue.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 150, y = 408, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_down_red.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 320, y = 178, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_left_blue.png",
				spriteColorRect = { x = 18, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 120, y = 420, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_left_red.png",
				spriteColorRect = { x = 18, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 32, y = 454, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_right_blue.png",
				spriteColorRect = { x = 23, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 276, y = 300, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_right_red.png",
				spriteColorRect = { x = 23, y = 7, width = 24, height = 56 }, 
				textureRect = { x = 74, y = 426, width = 24, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_up_blue.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 302, y = 294, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_move_up_red.png",
				spriteColorRect = { x = 22, y = 7, width = 20, height = 56 }, 
				textureRect = { x = 320, y = 236, width = 20, height = 56 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_spawn_blue_01.png",
				spriteColorRect = { x = 23, y = 44, width = 18, height = 20 }, 
				textureRect = { x = 192, y = 140, width = 18, height = 20 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_spawn_blue_02.png",
				spriteColorRect = { x = 17, y = 30, width = 24, height = 34 }, 
				textureRect = { x = 242, y = 360, width = 24, height = 34 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_spawn_blue_03.png",
				spriteColorRect = { x = 17, y = 14, width = 24, height = 50 }, 
				textureRect = { x = 212, y = 130, width = 24, height = 50 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_spawn_red_01.png",
				spriteColorRect = { x = 23, y = 44, width = 20, height = 20 }, 
				textureRect = { x = 100, y = 478, width = 20, height = 20 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_spawn_red_02.png",
				spriteColorRect = { x = 23, y = 30, width = 24, height = 34 }, 
				textureRect = { x = 338, y = 128, width = 24, height = 34 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "zombie_spawn_red_03.png",
				spriteColorRect = { x = 23, y = 14, width = 24, height = 50 }, 
				textureRect = { x = 186, y = 66, width = 24, height = 50 }, 
				spriteSourceSize = { width = 64, height = 64 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end