-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:2f9501eeecae8935108e10f1b8537991$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "arrow_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 2, y = 134, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrow_crossed_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 134, y = 68, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrow_crossed_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 68, y = 68, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrow_disabled_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 2, y = 68, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrow_disabled_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 2, y = 68, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrow_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 134, y = 2, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrow_selected_blue.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 68, y = 2, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "arrow_selected_red.png",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				textureRect = { x = 2, y = 2, width = 64, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "cemetery_blue.png",
				spriteColorRect = { x = 17, y = 2, width = 32, height = 58 },
				textureRect = { x = 2, y = 316, width = 32, height = 58 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "cemetery_red.png",
				spriteColorRect = { x = 17, y = 2, width = 32, height = 58 },
				textureRect = { x = 2, y = 376, width = 32, height = 58 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city1_blue.png",
				spriteColorRect = { x = 7, y = 16, width = 38, height = 48 },
				textureRect = { x = 100, y = 264, width = 38, height = 48 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city1_grey.png",
				spriteColorRect = { x = 7, y = 16, width = 38, height = 48 },
				textureRect = { x = 2, y = 266, width = 38, height = 48 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city1_red.png",
				spriteColorRect = { x = 7, y = 16, width = 38, height = 48 },
				textureRect = { x = 60, y = 264, width = 38, height = 48 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city2_blue.png",
				spriteColorRect = { x = 1, y = 0, width = 56, height = 64 },
				textureRect = { x = 2, y = 200, width = 56, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city2_grey.png",
				spriteColorRect = { x = 1, y = 0, width = 56, height = 64 },
				textureRect = { x = 184, y = 194, width = 56, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city2_red.png",
				spriteColorRect = { x = 1, y = 0, width = 56, height = 64 },
				textureRect = { x = 126, y = 134, width = 56, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city3_blue_01.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 },
				textureRect = { x = 110, y = 200, width = 48, height = 62 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city3_blue_02.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 },
				textureRect = { x = 60, y = 200, width = 48, height = 62 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city3_grey.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 },
				textureRect = { x = 200, y = 130, width = 48, height = 62 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city3_red_01.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 },
				textureRect = { x = 200, y = 66, width = 48, height = 62 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "city3_red_02.png",
				spriteColorRect = { x = 0, y = 1, width = 48, height = 62 },
				textureRect = { x = 200, y = 2, width = 48, height = 62 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fortress_wall_blue.png",
				spriteColorRect = { x = 4, y = 0, width = 56, height = 64 },
				textureRect = { x = 68, y = 134, width = 56, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "fortress_wall_red.png",
				spriteColorRect = { x = 4, y = 0, width = 56, height = 64 },
				textureRect = { x = 68, y = 134, width = 56, height = 64 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mana.png",
				spriteColorRect = { x = 19, y = 18, width = 26, height = 28 },
				textureRect = { x = 182, y = 352, width = 26, height = 28 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "mana_stack.png",
				spriteColorRect = { x = 10, y = 14, width = 46, height = 42 },
				textureRect = { x = 182, y = 308, width = 46, height = 42 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "pause.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 46 },
				textureRect = { x = 182, y = 260, width = 46, height = 46 },
				spriteSourceSize = { width = 46, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "zombie_attack_down_blue_01.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 160, y = 316, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_down_blue_02.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 112, y = 316, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_down_red_01.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 90, y = 316, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_down_red_02.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 68, y = 316, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_left_blue_01.png",
				spriteColorRect = { x = 11, y = 6, width = 30, height = 56 },
				textureRect = { x = 36, y = 316, width = 30, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_left_blue_02.png",
				spriteColorRect = { x = 17, y = 6, width = 24, height = 56 },
				textureRect = { x = 68, y = 376, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_left_red_01.png",
				spriteColorRect = { x = 11, y = 6, width = 30, height = 56 },
				textureRect = { x = 34, y = 436, width = 30, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_left_red_02.png",
				spriteColorRect = { x = 17, y = 6, width = 24, height = 56 },
				textureRect = { x = 66, y = 434, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_right_blue_01.png",
				spriteColorRect = { x = 22, y = 6, width = 30, height = 56 },
				textureRect = { x = 36, y = 376, width = 30, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_right_blue_02.png",
				spriteColorRect = { x = 22, y = 6, width = 24, height = 56 },
				textureRect = { x = 230, y = 318, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_right_red_01.png",
				spriteColorRect = { x = 22, y = 6, width = 30, height = 56 },
				textureRect = { x = 2, y = 436, width = 30, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_right_red_02.png",
				spriteColorRect = { x = 22, y = 6, width = 24, height = 56 },
				textureRect = { x = 230, y = 260, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_up_blue_01.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 94, y = 376, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_up_blue_02.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 92, y = 434, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_up_red_01.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 160, y = 258, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_attack_up_red_02.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 160, y = 200, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_carry_blue.png",
				spriteColorRect = { x = 17, y = 6, width = 24, height = 56 },
				textureRect = { x = 68, y = 376, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_carry_red.png",
				spriteColorRect = { x = 22, y = 6, width = 24, height = 56 },
				textureRect = { x = 230, y = 260, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_die_blue_01.png",
				spriteColorRect = { x = 17, y = 14, width = 24, height = 50 },
				textureRect = { x = 134, y = 314, width = 24, height = 50 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_die_blue_02.png",
				spriteColorRect = { x = 17, y = 30, width = 24, height = 34 },
				textureRect = { x = 158, y = 432, width = 24, height = 34 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_die_blue_03.png",
				spriteColorRect = { x = 23, y = 44, width = 18, height = 20 },
				textureRect = { x = 140, y = 264, width = 18, height = 20 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_die_red_01.png",
				spriteColorRect = { x = 22, y = 13, width = 24, height = 50 },
				textureRect = { x = 134, y = 366, width = 24, height = 50 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_die_red_02.png",
				spriteColorRect = { x = 22, y = 30, width = 24, height = 34 },
				textureRect = { x = 136, y = 476, width = 24, height = 34 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_die_red_03.png",
				spriteColorRect = { x = 22, y = 44, width = 20, height = 20 },
				textureRect = { x = 162, y = 468, width = 20, height = 20 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_down_blue.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 210, y = 376, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_down_red.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 136, y = 418, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_left_blue.png",
				spriteColorRect = { x = 17, y = 6, width = 24, height = 56 },
				textureRect = { x = 68, y = 376, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_left_red.png",
				spriteColorRect = { x = 17, y = 6, width = 24, height = 56 },
				textureRect = { x = 66, y = 434, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_right_blue.png",
				spriteColorRect = { x = 22, y = 6, width = 24, height = 56 },
				textureRect = { x = 230, y = 318, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_right_red.png",
				spriteColorRect = { x = 22, y = 6, width = 24, height = 56 },
				textureRect = { x = 230, y = 260, width = 24, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_up_blue.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 160, y = 374, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_move_up_red.png",
				spriteColorRect = { x = 22, y = 6, width = 20, height = 56 },
				textureRect = { x = 114, y = 434, width = 20, height = 56 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_spawn_blue_01.png",
				spriteColorRect = { x = 23, y = 44, width = 18, height = 20 },
				textureRect = { x = 140, y = 264, width = 18, height = 20 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_spawn_blue_02.png",
				spriteColorRect = { x = 17, y = 30, width = 24, height = 34 },
				textureRect = { x = 158, y = 432, width = 24, height = 34 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_spawn_blue_03.png",
				spriteColorRect = { x = 17, y = 14, width = 24, height = 50 },
				textureRect = { x = 134, y = 314, width = 24, height = 50 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_spawn_red_01.png",
				spriteColorRect = { x = 22, y = 44, width = 20, height = 20 },
				textureRect = { x = 162, y = 468, width = 20, height = 20 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_spawn_red_02.png",
				spriteColorRect = { x = 22, y = 30, width = 24, height = 34 },
				textureRect = { x = 136, y = 476, width = 24, height = 34 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "zombie_spawn_red_03.png",
				spriteColorRect = { x = 22, y = 13, width = 24, height = 50 },
				textureRect = { x = 134, y = 366, width = 24, height = 50 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

